# Generated by Django 5.0 on 2023-12-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcoder', '0003_playlist_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videos',
            new_name='Video',
        ),
    ]
