# Generated by Django 5.0 on 2024-01-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoder', '0004_rename_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(max_length=250),
        ),
    ]
