# Generated by Django 5.0 on 2024-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoder', '0005_alter_playlist_thumbnail_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.CharField(max_length=300),
        ),
    ]
