# Generated by Django 5.2 on 2026-02-22 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoder', '0006_playlist_owner_video_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_queries', models.JSONField(blank=True, default=list)),
                ('category_affiliation', models.JSONField(blank=True, default=dict, help_text="e.g. {'Django': 5, 'Python': 3}")),
                ('total_watch_time', models.PositiveIntegerField(default=0)),
                ('liked_blogs', models.ManyToManyField(blank=True, related_name='liked_by_users', to='opcoder.blog')),
                ('liked_videos', models.ManyToManyField(blank=True, related_name='liked_by_users', to='opcoder.video')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL)),
                ('viewed_blogs', models.ManyToManyField(blank=True, related_name='viewed_by_users', to='opcoder.blog')),
                ('viewed_videos', models.ManyToManyField(blank=True, related_name='viewed_by_users', to='opcoder.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_watch_time', models.FloatField(default=0.0, help_text='Average watch time in seconds')),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='opcoder.video')),
            ],
        ),
    ]
